export enum ContactoEstado {
  PENDIENTE = 'PENDIENTE',
  NUEVA = 'NUEVA',
  VISTA = 'VISTA',
  SOLUCIONADA = 'SOLUCIONADA',
  CONTACTADO = 'CONTACTADO',
  RESUELTO = 'RESUELTO',
  RECHAZADO = 'RECHAZADO'
}
